services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
